name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Build CLI version
      run: cargo build --release
      
    - name: Build WASM version
      run: |
        chmod +x build_web.sh
        ./build_web.sh
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v3
      
    - name: Upload to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./docs
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: actions/deploy-pages@v2
        
    - name: Upload CLI binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: vn-recommender-cli
        path: target/release/visual_novel_recommendation_engine
